In [25]:
import numpy as np

def mat_string_to_mat(matrix_string):
    arr = []
    for line in matrix_string.split('\n'):
        line = line.split()
        if len(line) > 0:
            line = list(map(int, line))
            arr.append(line)
    arr = np.array(arr) 
    print(arr)
    return arr

def sign_ext(num):
    if num < 0:
        return -1
    if num > 0:
        return 1
    return 0

def mat_to_edgelist(matrix_string, indexing=1):
    mat_repr = mat_string_to_mat(matrix_string)
    edgelist = ''
    for u, row  in enumerate(mat_repr):
        for v, col in enumerate(row):
            sign = sign_ext(col)
            if sign != 0:
                edgelist += '{0},{1},{2}\n'.format(u + indexing, v + indexing, sign)
    return edgelist
    

def matrix_file_to_edgelist_file(input_file, output_file):
    with open(input_file, 'r') as infp:
        with open(output_file, 'w') as outfp:
            mat_string = infp.read()
            print(mat_string)
            edgelist = mat_to_edgelist(mat_string)
            outfp.write(edgelist)

In [26]:
dataset = 'sampson'
in_filename = f'../data/comm/{dataset}-mat.txt'
out_filename = f'../data/comm/{dataset}-cleaned.txt'


In [27]:
matrix_file_to_edgelist_file(in_filename, out_filename)

0 0 2 0 3 -2 -1 0 0 -3 0 0 0 1 0 0 0 0
3 0 0 0 0 0 2 0 0 -1 0 0 -3 1 0 0 -2 0
2 3 0 -1 0 0 0 -3 -2 0 0 0 0 0 0 0 1 0 
0 0 -2 0 3 1 -3 0 0 2 0 0 0 0 0 0 0 -1
0 0 0 3 0 0 0 0 0 0 2 0 1 0 0 0 0 0 
1 0 0 3 0 0 -3 -1 2 0 0 -2 0 0 0 0 0 0
0 2 0 -3 -1 -2 0 1 0 0 0 0 0 0 0 3 0 0
3 2 -3 0 0 0 0 0 1 0 0 0 0 -2 0 0 -1 0
0 0 -3 0 2 0 0 3 0 0 0 0 0 0 0 1 -2 -1 
0 0 0 3 0 0 0 1 0 0 0 0 0 2 0 0 0 0
0 0 -1 0 3 0 0 1 0 0 0 0 -3 2 0 0 -2 0
3 2 -1 -3 0 0 0 0 0 0 -2 0 0 1 0 0 0 0
0 -3 0 0 2 -2 1 0 0 0 0 -1 0 0 0 0 0 3
3 0 0 0 0 0 0 -2 0 0 1 2 -3 0 2 0 -1 0
3 2 -2 0 0 0 0 0 0 0 0 0 -3 1 0 0 -1 -1
1 2 0 0 0 0 3 0 0 0 0 0 -1 0 0 0 -3 -2
0 0 3 -3 -2 0 0 0 0 0 -1 0 2 0 0 0 0 1
2 3 0 -3 0 -2 1 0 0 0 0 0 0 0 0 -1 0 0



[[ 0  0  2  0  3 -2 -1  0  0 -3  0  0  0  1  0  0  0  0]
 [ 3  0  0  0  0  0  2  0  0 -1  0  0 -3  1  0  0 -2  0]
 [ 2  3  0 -1  0  0  0 -3 -2  0  0  0  0  0  0  0  1  0]
 [ 0  0 -2  0  3  1 -3  0  0  2  0  0  0  0  0  0  0 -1]
 [ 0  0  0  3  0  0  0  0  0  0  2  0  1  0  0  0  0  0]
 [ 1  0  0  

In [28]:
\lambda 

SyntaxError: unexpected character after line continuation character (<ipython-input-28-f6e5f9db2541>, line 1)